
services:
  wordpress:
    image: wordpress:latest
    restart: no
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-theme:/var/www/html/wp-content/themes/bis-theme
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: no
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: wordpress_root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
